### ISSUE TITLE
Cleaning up drop-down vs. map vs. hover country names

### ISSUE THREAD

**Issue by els2171** [tsdataclinic/AfricaCovidDashboard#225]
Breakdown of differences: https://docs.google.com/spreadsheets/d/1Bw1V9dGoBq2NmtVGR6SPFuqOO3onCb7JSbdsCnuyKe8/edit?usp=sharing

To do: discuss what's required to change; prioritize standard with @stuartlynn

**Comment by stuartlynn** [comment]
This should be resolved with #227 @els2171 can you double check to see if I missed anything
